apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: services-whatsapp-butler
build:
  local:
    push: false
    tryImportMissing: false
    useBuildkit: true
    concurrency: 64
  artifacts:
    - image: gcr.io/trash-362115/whatsapp-api
      context: ../../../services/butler/whatsapp-mcp/
      docker:
        dockerfile: Dockerfile
    - image: gcr.io/trash-362115/whatsapp-mcp
      context: ../../../services/butler/whatsapp-mcp/
      docker:
        dockerfile: Dockerfile

profiles:
- name: production
  build:
    platforms: ["linux/amd64"]
    local:
      push: true

