apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: services-agent-butler
build:
  local:
    push: false
    tryImportMissing: false
    useBuildkit: true
    concurrency: 64
  artifacts:
    - image: gcr.io/trash-362115/services-agent-butler
      context: ../../../services/butler/agent
      docker:
        dockerfile: Dockerfile

profiles:
- name: production
  build:
    platforms: ["linux/amd64"]
    local:
      push: true

